on: [push]
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_10.3.app
    - name: build
      run: |
        cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
        Scripts/build.py release
        cd build/Release
        zip -r GitX GitX.app/
    - uses: actions/upload-artifact@v1
      with:
        name: GitX
        path: build/Release/GitX.zip
